<?php

namespace Database\Seeders;

use App\Models\Country;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Country::truncate();

        $countries = [
            // Records 01-99 (Afghanistan to India]

            ['name' => 'Afghanistan', 'code' => 'AFG', 'num_code' => '4', 'phone_code' => '93'],
            ['name' => 'Albania', 'code' => 'ALB', 'num_code' => '8', 'phone_code' => '355'],
            ['name' => 'Algeria', 'code' => 'DZA', 'num_code' => '12', 'phone_code' => '213'],
            ['name' => 'American Samoa', 'code' => 'ASM', 'num_code' => '16', 'phone_code' => '1684'],
            ['name' => 'Andorra', 'code' => 'AND', 'num_code' => '20', 'phone_code' => '376'],
            ['name' => 'Angola', 'code' => 'AGO', 'num_code' => '24', 'phone_code' => '244'],
            ['name' => 'Anguilla', 'code' => 'AIA', 'num_code' => '660', 'phone_code' => '1264'],
            ['name' => 'Antigua and Barbuda', 'code' => 'ATG', 'num_code' => '28', 'phone_code' => '1268'],
            ['name' => 'Argentina', 'code' => 'ARG', 'num_code' => '32', 'phone_code' => '54'],
            ['name' => 'Armenia', 'code' => 'ARM', 'num_code' => '51', 'phone_code' => '374'],
            ['name' => 'Aruba', 'code' => 'ABW', 'num_code' => '533', 'phone_code' => '297'],
            ['name' => 'Australia', 'code' => 'AUS', 'num_code' => '36', 'phone_code' => '61'],
            ['name' => 'Austria', 'code' => 'AUT', 'num_code' => '40', 'phone_code' => '43'],
            ['name' => 'Azerbaijan', 'code' => 'AZE', 'num_code' => '31', 'phone_code' => '994'],
            ['name' => 'Bahamas', 'code' => 'BHS', 'num_code' => '44', 'phone_code' => '1242'],
            ['name' => 'Bahrain', 'code' => 'BHR', 'num_code' => '48', 'phone_code' => '973'],
            ['name' => 'Bangladesh', 'code' => 'BGD', 'num_code' => '50', 'phone_code' => '880'],
            ['name' => 'Barbados', 'code' => 'BRB', 'num_code' => '52', 'phone_code' => '1246'],
            ['name' => 'Belarus', 'code' => 'BLR', 'num_code' => '112', 'phone_code' => '375'],
            ['name' => 'Belgium', 'code' => 'BEL', 'num_code' => '56', 'phone_code' => '32'],
            ['name' => 'Belize', 'code' => 'BLZ', 'num_code' => '84', 'phone_code' => '501'],
            ['name' => 'Benin', 'code' => 'BEN', 'num_code' => '204', 'phone_code' => '229'],
            ['name' => 'Bermuda', 'code' => 'BMU', 'num_code' => '60', 'phone_code' => '1441'],
            ['name' => 'Bhutan', 'code' => 'BTN', 'num_code' => '64', 'phone_code' => '975'],
            ['name' => 'Bolivia', 'code' => 'BOL', 'num_code' => '68', 'phone_code' => '591'],
            ['name' => 'Bosnia and Herzegovina', 'code' => 'BIH', 'num_code' => '70', 'phone_code' => '387'],
            ['name' => 'Botswana', 'code' => 'BWA', 'num_code' => '72', 'phone_code' => '267'],


            ['name' => 'Brazil', 'code' => 'BRA', 'num_code' => '76', 'phone_code' => '55'],
            ['name' => 'Brunei Darussalam', 'code' => 'BRN', 'num_code' => '96', 'phone_code' => '673'],
            ['name' => 'Bulgaria', 'code' => 'BGR', 'num_code' => '100', 'phone_code' => '359'],
            ['name' => 'Burkina Faso', 'code' => 'BFA', 'num_code' => '854', 'phone_code' => '226'],
            ['name' => 'Burundi', 'code' => 'BDI', 'num_code' => '108', 'phone_code' => '257'],
            ['name' => 'Cambodia', 'code' => 'KHM', 'num_code' => '116', 'phone_code' => '855'],
            ['name' => 'Cameroon', 'code' => 'CMR', 'num_code' => '120', 'phone_code' => '237'],
            ['name' => 'Canada', 'code' => 'CAN', 'num_code' => '124', 'phone_code' => '1'],
            ['name' => 'Cape Verde', 'code' => 'CPV', 'num_code' => '132', 'phone_code' => '238'],
            ['name' => 'Cayman Islands', 'code' => 'CYM', 'num_code' => '136', 'phone_code' => '1345'],
            ['name' => 'Central African Republic', 'code' => 'CAF', 'num_code' => '140', 'phone_code' => '236'],
            ['name' => 'Chad', 'code' => 'TCD', 'num_code' => '148', 'phone_code' => '235'],
            ['name' => 'Chile', 'code' => 'CHL', 'num_code' => '152', 'phone_code' => '56'],
            ['name' => 'China', 'code' => 'CHN', 'num_code' => '156', 'phone_code' => '86'],
            ['name' => 'Colombia', 'code' => 'COL', 'num_code' => '170', 'phone_code' => '57'],
            ['name' => 'Comoros', 'code' => 'COM', 'num_code' => '174', 'phone_code' => '269'],
            ['name' => 'Congo', 'code' => 'COG', 'num_code' => '178', 'phone_code' => '242'],
            ['name' => 'Congo, the Democratic Republic of the', 'code' => 'COD', 'num_code' => '180', 'phone_code' => '242'],
            ['name' => 'Cook Islands', 'code' => 'COK', 'num_code' => '184', 'phone_code' => '682'],
            ['name' => 'Costa Rica', 'code' => 'CRI', 'num_code' => '188', 'phone_code' => '506'],
            ['name' => 'Cote D\'Ivoire', 'code' => 'CIV', 'num_code' => '384', 'phone_code' => '225'],
            ['name' => 'Croatia', 'code' => 'HRV', 'num_code' => '191', 'phone_code' => '385'],
            ['name' => 'Cuba', 'code' => 'CUB', 'num_code' => '192', 'phone_code' => '53'],
            ['name' => 'Cyprus', 'code' => 'CYP', 'num_code' => '196', 'phone_code' => '357'],
            ['name' => 'Czech Republic', 'code' => 'CZE', 'num_code' => '203', 'phone_code' => '420'],
            ['name' => 'Denmark', 'code' => 'DNK', 'num_code' => '208', 'phone_code' => '45'],
            ['name' => 'Djibouti', 'code' => 'DJI', 'num_code' => '262', 'phone_code' => '253'],

            ['name' => 'Dominica', 'code' => 'DMA', 'num_code' => '212', 'phone_code' => '1767'],
            ['name' => 'Dominican Republic', 'code' => 'DOM', 'num_code' => '214', 'phone_code' => '1809'],
            ['name' => 'Ecuador', 'code' => 'ECU', 'num_code' => '218', 'phone_code' => '593'],
            ['name' => 'Egypt', 'code' => 'EGY', 'num_code' => '818', 'phone_code' => '20'],
            ['name' => 'El Salvador', 'code' => 'SLV', 'num_code' => '222', 'phone_code' => '503'],
            ['name' => 'Equatorial Guinea', 'code' => 'GNQ', 'num_code' => '226', 'phone_code' => '240'],
            ['name' => 'Eritrea', 'code' => 'ERI', 'num_code' => '232', 'phone_code' => '291'],
            ['name' => 'Estonia', 'code' => 'EST', 'num_code' => '233', 'phone_code' => '372'],
            ['name' => 'Ethiopia', 'code' => 'ETH', 'num_code' => '231', 'phone_code' => '251'],
            ['name' => 'Falkland Islands (Malvinas]', 'code' => 'FLK', 'num_code' => '238', 'phone_code' => '500'],
            ['name' => 'Faroe Islands', 'code' => 'FRO', 'num_code' => '234', 'phone_code' => '298'],
            ['name' => 'Fiji', 'code' => 'FJI', 'num_code' => '242', 'phone_code' => '679'],
            ['name' => 'Finland', 'code' => 'FIN', 'num_code' => '246', 'phone_code' => '358'],
            ['name' => 'France', 'code' => 'FRA', 'num_code' => '250', 'phone_code' => '33'],
            ['name' => 'French Guiana', 'code' => 'GUF', 'num_code' => '254', 'phone_code' => '594'],
            ['name' => 'French Polynesia', 'code' => 'PYF', 'num_code' => '258', 'phone_code' => '689'],
            ['name' => 'Gabon', 'code' => 'GAB', 'num_code' => '266', 'phone_code' => '241'],
            ['name' => 'Gambia', 'code' => 'GMB', 'num_code' => '270', 'phone_code' => '220'],
            ['name' => 'Georgia', 'code' => 'GEO', 'num_code' => '268', 'phone_code' => '995'],
            ['name' => 'Germany', 'code' => 'DEU', 'num_code' => '276', 'phone_code' => '49'],
            ['name' => 'Ghana', 'code' => 'GHA', 'num_code' => '288', 'phone_code' => '233'],
            ['name' => 'Gibraltar', 'code' => 'GIB', 'num_code' => '292', 'phone_code' => '350'],
            ['name' => 'Greece', 'code' => 'GRC', 'num_code' => '300', 'phone_code' => '30'],
            ['name' => 'Greenland', 'code' => 'GRL', 'num_code' => '304', 'phone_code' => '299'],
            ['name' => 'Grenada', 'code' => 'GRD', 'num_code' => '308', 'phone_code' => '1473'],
            ['name' => 'Guadeloupe', 'code' => 'GLP', 'num_code' => '312', 'phone_code' => '590'],
            ['name' => 'Guam', 'code' => 'GUM', 'num_code' => '316', 'phone_code' => '1671'],
            ['name' => 'Guatemala', 'code' => 'GTM', 'num_code' => '320', 'phone_code' => '502'],
            ['name' => 'Guinea', 'code' => 'GIN', 'num_code' => '324', 'phone_code' => '224'],
            ['name' => 'Guinea-Bissau', 'code' => 'GNB', 'num_code' => '624', 'phone_code' => '245'],
            ['name' => 'Guyana', 'code' => 'GUY', 'num_code' => '328', 'phone_code' => '592'],
            ['name' => 'Haiti', 'code' => 'HTI', 'num_code' => '332', 'phone_code' => '509'],
            ['name' => 'Holy See (Vatican City State]', 'code' => 'VAT', 'num_code' => '336', 'phone_code' => '39'],
            ['name' => 'Honduras', 'code' => 'HND', 'num_code' => '340', 'phone_code' => '504'],
            ['name' => 'Hong Kong', 'code' => 'HKG', 'num_code' => '344', 'phone_code' => '852'],
            ['name' => 'Hungary', 'code' => 'HUN', 'num_code' => '348', 'phone_code' => '36'],
            ['name' => 'Iceland', 'code' => 'ISL', 'num_code' => '352', 'phone_code' => '354'],
            ['name' => 'India', 'code' => 'IND', 'num_code' => '356', 'phone_code' => '91'],


            // Records 100-199 (Indonesia to Spain]

            ['name' => 'Indonesia', 'code' => 'IDN', 'num_code' => '360', 'phone_code' => '62'],
            ['name' => 'Iran, Islamic Republic of', 'code' => 'IRN', 'num_code' => '364', 'phone_code' => '98'],
            ['name' => 'Iraq', 'code' => 'IRQ', 'num_code' => '368', 'phone_code' => '964'],
            ['name' => 'Ireland', 'code' => 'IRL', 'num_code' => '372', 'phone_code' => '353'],
            ['name' => 'Israel', 'code' => 'ISR', 'num_code' => '376', 'phone_code' => '972'],
            ['name' => 'Italy', 'code' => 'ITA', 'num_code' => '380', 'phone_code' => '39'],
            ['name' => 'Jamaica', 'code' => 'JAM', 'num_code' => '388', 'phone_code' => '1876'],
            ['name' => 'Japan', 'code' => 'JPN', 'num_code' => '392', 'phone_code' => '81'],
            ['name' => 'Jordan', 'code' => 'JOR', 'num_code' => '400', 'phone_code' => '962'],
            ['name' => 'Kazakhstan', 'code' => 'KAZ', 'num_code' => '398', 'phone_code' => '7'],
            ['name' => 'Kenya', 'code' => 'KEN', 'num_code' => '404', 'phone_code' => '254'],
            ['name' => 'Kiribati', 'code' => 'KIR', 'num_code' => '296', 'phone_code' => '686'],
            ['name' => 'Korea, Democratic People\'s Republic of', 'code' => 'PRK', 'num_code' => '408', 'phone_code' => '850'],
            ['name' => 'Korea, Republic of', 'code' => 'KOR', 'num_code' => '410', 'phone_code' => '82'],
            ['name' => 'Kuwait', 'code' => 'KWT', 'num_code' => '414', 'phone_code' => '965'],
            ['name' => 'Kyrgyzstan', 'code' => 'KGZ', 'num_code' => '417', 'phone_code' => '996'],
            ['name' => 'Lao People\'s Democratic Republic', 'code' => 'LAO', 'num_code' => '418', 'phone_code' => '856'],
            ['name' => 'Latvia', 'code' => 'LVA', 'num_code' => '428', 'phone_code' => '371'],
            ['name' => 'Lebanon', 'code' => 'LBN', 'num_code' => '422', 'phone_code' => '961'],
            ['name' => 'Lesotho', 'code' => 'LSO', 'num_code' => '426', 'phone_code' => '266'],
            ['name' => 'Liberia', 'code' => 'LBR', 'num_code' => '430', 'phone_code' => '231'],
            ['name' => 'Libyan Arab Jamahiriya', 'code' => 'LBY', 'num_code' => '434', 'phone_code' => '218'],
            ['name' => 'Liechtenstein', 'code' => 'LIE', 'num_code' => '438', 'phone_code' => '423'],
            ['name' => 'Lithuania', 'code' => 'LTU', 'num_code' => '440', 'phone_code' => '370'],
            ['name' => 'Luxembourg', 'code' => 'LUX', 'num_code' => '442', 'phone_code' => '352'],
            ['name' => 'Macao', 'code' => 'MAC', 'num_code' => '446', 'phone_code' => '853'],
            ['name' => 'Macedonia, the Former Yugoslav Republic of', 'code' => 'MKD', 'num_code' => '807', 'phone_code' => '389'],
            ['name' => 'Madagascar', 'code' => 'MDG', 'num_code' => '450', 'phone_code' => '261'],
            ['name' => 'Malawi', 'code' => 'MWI', 'num_code' => '454', 'phone_code' => '265'],
            ['name' => 'Malaysia', 'code' => 'MYS', 'num_code' => '458', 'phone_code' => '60'],
            ['name' => 'Maldives', 'code' => 'MDV', 'num_code' => '462', 'phone_code' => '960'],
            ['name' => 'Mali', 'code' => 'MLI', 'num_code' => '466', 'phone_code' => '223'],
            ['name' => 'Malta', 'code' => 'MLT', 'num_code' => '470', 'phone_code' => '356'],
            ['name' => 'Marshall Islands', 'code' => 'MHL', 'num_code' => '584', 'phone_code' => '692'],
            ['name' => 'Martinique', 'code' => 'MTQ', 'num_code' => '474', 'phone_code' => '596'],
            ['name' => 'Mauritania', 'code' => 'MRT', 'num_code' => '478', 'phone_code' => '222'],
            ['name' => 'Mauritius', 'code' => 'MUS', 'num_code' => '480', 'phone_code' => '230'],
            ['name' => 'Mexico', 'code' => 'MEX', 'num_code' => '484', 'phone_code' => '52'],
            ['name' => 'Micronesia, Federated States of', 'code' => 'FSM', 'num_code' => '583', 'phone_code' => '691'],
            ['name' => 'Moldova, Republic of', 'code' => 'MDA', 'num_code' => '498', 'phone_code' => '373'],
            ['name' => 'Monaco', 'code' => 'MCO', 'num_code' => '492', 'phone_code' => '377'],
            ['name' => 'Mongolia', 'code' => 'MNG', 'num_code' => '496', 'phone_code' => '976'],
            ['name' => 'Montserrat', 'code' => 'MSR', 'num_code' => '500', 'phone_code' => '1664'],
            ['name' => 'Morocco', 'code' => 'MAR', 'num_code' => '504', 'phone_code' => '212'],
            ['name' => 'Mozambique', 'code' => 'MOZ', 'num_code' => '508', 'phone_code' => '258'],
            ['name' => 'Myanmar', 'code' => 'MMR', 'num_code' => '104', 'phone_code' => '95'],
            ['name' => 'Namibia', 'code' => 'NAM', 'num_code' => '516', 'phone_code' => '264'],
            ['name' => 'Nauru', 'code' => 'NRU', 'num_code' => '520', 'phone_code' => '674'],
            ['name' => 'Nepal', 'code' => 'NPL', 'num_code' => '524', 'phone_code' => '977'],
            ['name' => 'Netherlands', 'code' => 'NLD', 'num_code' => '528', 'phone_code' => '31'],
            ['name' => 'Netherlands Antilles', 'code' => 'ANT', 'num_code' => '530', 'phone_code' => '599'],
            ['name' => 'New Caledonia', 'code' => 'NCL', 'num_code' => '540', 'phone_code' => '687'],
            ['name' => 'New Zealand', 'code' => 'NZL', 'num_code' => '554', 'phone_code' => '64'],
            ['name' => 'Nicaragua', 'code' => 'NIC', 'num_code' => '558', 'phone_code' => '505'],
            ['name' => 'Niger', 'code' => 'NER', 'num_code' => '562', 'phone_code' => '227'],
            ['name' => 'Nigeria', 'code' => 'NGA', 'num_code' => '566', 'phone_code' => '234'],
            ['name' => 'Niue', 'code' => 'NIU', 'num_code' => '570', 'phone_code' => '683'],
            ['name' => 'Norfolk Island', 'code' => 'NFK', 'num_code' => '574', 'phone_code' => '672'],
            ['name' => 'Northern Mariana Islands', 'code' => 'MNP', 'num_code' => '580', 'phone_code' => '1670'],
            ['name' => 'Norway', 'code' => 'NOR', 'num_code' => '578', 'phone_code' => '47'],
            ['name' => 'Oman', 'code' => 'OMN', 'num_code' => '512', 'phone_code' => '968'],
            ['name' => 'Pakistan', 'code' => 'PAK', 'num_code' => '586', 'phone_code' => '92'],
            ['name' => 'Palau', 'code' => 'PLW', 'num_code' => '585', 'phone_code' => '680'],
            ['name' => 'Panama', 'code' => 'PAN', 'num_code' => '591', 'phone_code' => '507'],
            ['name' => 'Papua New Guinea', 'code' => 'PNG', 'num_code' => '598', 'phone_code' => '675'],
            ['name' => 'Paraguay', 'code' => 'PRY', 'num_code' => '600', 'phone_code' => '595'],
            ['name' => 'Peru', 'code' => 'PER', 'num_code' => '604', 'phone_code' => '51'],
            ['name' => 'Philippines', 'code' => 'PHL', 'num_code' => '608', 'phone_code' => '63'],
            ['name' => 'Pitcairn', 'code' => 'PCN', 'num_code' => '612', 'phone_code' => '0'],
            ['name' => 'Poland', 'code' => 'POL', 'num_code' => '616', 'phone_code' => '48'],
            ['name' => 'Portugal', 'code' => 'PRT', 'num_code' => '620', 'phone_code' => '351'],
            ['name' => 'Puerto Rico', 'code' => 'PRI', 'num_code' => '630', 'phone_code' => '1787'],
            ['name' => 'Qatar', 'code' => 'QAT', 'num_code' => '634', 'phone_code' => '974'],
            ['name' => 'Reunion', 'code' => 'REU', 'num_code' => '638', 'phone_code' => '262'],
            ['name' => 'Romania', 'code' => 'ROM', 'num_code' => '642', 'phone_code' => '40'],
            ['name' => 'Russian Federation', 'code' => 'RUS', 'num_code' => '643', 'phone_code' => '70'],
            ['name' => 'Rwanda', 'code' => 'RWA', 'num_code' => '646', 'phone_code' => '250'],
            ['name' => 'Saint Helena', 'code' => 'SHN', 'num_code' => '654', 'phone_code' => '290'],
            ['name' => 'Saint Kitts and Nevis', 'code' => 'KNA', 'num_code' => '659', 'phone_code' => '1869'],
            ['name' => 'Saint Lucia', 'code' => 'LCA', 'num_code' => '662', 'phone_code' => '1758'],
            ['name' => 'Saint Pierre and Miquelon', 'code' => 'SPM', 'num_code' => '666', 'phone_code' => '508'],
            ['name' => 'Saint Vincent and the Grenadines', 'code' => 'VCT', 'num_code' => '670', 'phone_code' => '1784'],
            ['name' => 'Samoa', 'code' => 'WSM', 'num_code' => '882', 'phone_code' => '684'],
            ['name' => 'San Marino', 'code' => 'SMR', 'num_code' => '674', 'phone_code' => '378'],
            ['name' => 'Sao Tome and Principe', 'code' => 'STP', 'num_code' => '678', 'phone_code' => '239'],
            ['name' => 'Saudi Arabia', 'code' => 'SAU', 'num_code' => '682', 'phone_code' => '966'],
            ['name' => 'Senegal', 'code' => 'SEN', 'num_code' => '686', 'phone_code' => '221'],
            ['name' => 'Seychelles', 'code' => 'SYC', 'num_code' => '690', 'phone_code' => '248'],
            ['name' => 'Sierra Leone', 'code' => 'SLE', 'num_code' => '694', 'phone_code' => '232'],
            ['name' => 'Singapore', 'code' => 'SGP', 'num_code' => '702', 'phone_code' => '65'],
            ['name' => 'Slovakia', 'code' => 'SVK', 'num_code' => '703', 'phone_code' => '421'],
            ['name' => 'Slovenia', 'code' => 'SVN', 'num_code' => '705', 'phone_code' => '386'],
            ['name' => 'Solomon Islands', 'code' => 'SLB', 'num_code' => '90', 'phone_code' => '677'],
            ['name' => 'Somalia', 'code' => 'SOM', 'num_code' => '706', 'phone_code' => '252'],
            ['name' => 'South Africa', 'code' => 'ZAF', 'num_code' => '710', 'phone_code' => '27'],
            ['name' => 'Spain', 'code' => 'ESP', 'num_code' => '724', 'phone_code' => '34'],
            ['name' => 'Sri Lanka', 'code' => 'LKA', 'num_code' => '144', 'phone_code' => '94'],
            ['name' => 'Sudan', 'code' => 'SDN', 'num_code' => '736', 'phone_code' => '249'],
            ['name' => 'Suriname', 'code' => 'SUR', 'num_code' => '740', 'phone_code' => '597'],
            ['name' => 'Svalbard and Jan Mayen', 'code' => 'SJM', 'num_code' => '744', 'phone_code' => '47'],
            ['name' => 'Swaziland', 'code' => 'SWZ', 'num_code' => '748', 'phone_code' => '268'],
            ['name' => 'Sweden', 'code' => 'SWE', 'num_code' => '752', 'phone_code' => '46'],
            ['name' => 'Switzerland', 'code' => 'CHE', 'num_code' => '756', 'phone_code' => '41'],
            ['name' => 'Syrian Arab Republic', 'code' => 'SYR', 'num_code' => '760', 'phone_code' => '963'],
            ['name' => 'Taiwan, Province of China', 'code' => 'TWN', 'num_code' => '158', 'phone_code' => '886'],
            ['name' => 'Tajikistan', 'code' => 'TJK', 'num_code' => '762', 'phone_code' => '992'],
            ['name' => 'Tanzania, United Republic of', 'code' => 'TZA', 'num_code' => '834', 'phone_code' => '255'],
            ['name' => 'Thailand', 'code' => 'THA', 'num_code' => '764', 'phone_code' => '66'],
            ['name' => 'Togo', 'code' => 'TGO', 'num_code' => '768', 'phone_code' => '228'],
            ['name' => 'Tokelau', 'code' => 'TKL', 'num_code' => '772', 'phone_code' => '690'],
            ['name' => 'Tonga', 'code' => 'TON', 'num_code' => '776', 'phone_code' => '676'],
            ['name' => 'Trinidad and Tobago', 'code' => 'TTO', 'num_code' => '780', 'phone_code' => '1868'],
            ['name' => 'Tunisia', 'code' => 'TUN', 'num_code' => '788', 'phone_code' => '216'],
            ['name' => 'Turkey', 'code' => 'TUR', 'num_code' => '792', 'phone_code' => '90'],
            ['name' => 'Turkmenistan', 'code' => 'TKM', 'num_code' => '795', 'phone_code' => '7370'],
            ['name' => 'Turks and Caicos Islands', 'code' => 'TCA', 'num_code' => '796', 'phone_code' => '1649'],
            ['name' => 'Tuvalu', 'code' => 'TUV', 'num_code' => '798', 'phone_code' => '688'],
            ['name' => 'Uganda', 'code' => 'UGA', 'num_code' => '800', 'phone_code' => '256'],
            ['name' => 'Ukraine', 'code' => 'UKR', 'num_code' => '804', 'phone_code' => '380'],
            ['name' => 'United Arab Emirates', 'code' => 'ARE', 'num_code' => '784', 'phone_code' => '971'],
            ['name' => 'United Kingdom', 'code' => 'GBR', 'num_code' => '826', 'phone_code' => '44'],
            ['name' => 'United States', 'code' => 'USA', 'num_code' => '840', 'phone_code' => '1'],
            ['name' => 'Uruguay', 'code' => 'URY', 'num_code' => '858', 'phone_code' => '598'],
            ['name' => 'Uzbekistan', 'code' => 'UZB', 'num_code' => '860', 'phone_code' => '998'],
            ['name' => 'Vanuatu', 'code' => 'VUT', 'num_code' => '548', 'phone_code' => '678'],
            ['name' => 'Venezuela', 'code' => 'VEN', 'num_code' => '862', 'phone_code' => '58'],
            ['name' => 'Viet Nam', 'code' => 'VNM', 'num_code' => '704', 'phone_code' => '84'],
            ['name' => 'Virgin Islands, British', 'code' => 'VGB', 'num_code' => '92', 'phone_code' => '1284'],
            ['name' => 'Virgin Islands, U.S.', 'code' => 'VIR', 'num_code' => '850', 'phone_code' => '1340'],
            ['name' => 'Wallis and Futuna', 'code' => 'WLF', 'num_code' => '876', 'phone_code' => '681'],
            ['name' => 'Western Sahara', 'code' => 'ESH', 'num_code' => '732', 'phone_code' => '212'],
            ['name' => 'Yemen', 'code' => 'YEM', 'num_code' => '887', 'phone_code' => '967'],
            ['name' => 'Zambia', 'code' => 'ZMB', 'num_code' => '894', 'phone_code' => '260'],
            ['name' => 'Zimbabwe', 'code' => 'ZWE', 'num_code' => '716', 'phone_code' => '263'],
            ['name' => 'Serbia', 'code' => 'SRB', 'num_code' => '688', 'phone_code' => '381'],
            ['name' => 'Asia / Pacific Region', 'code' => '0', 'num_code' => '0', 'phone_code' => '0'],
            ['name' => 'Montenegro', 'code' => 'MNE', 'num_code' => '499', 'phone_code' => '382'],
            ['name' => 'Aland Islands', 'code' => 'ALA', 'num_code' => '248', 'phone_code' => '358'],
            ['name' => 'Bonaire, Sint Eustatius and Saba', 'code' => 'BES', 'num_code' => '535', 'phone_code' => '599'],
            ['name' => 'Curacao', 'code' => 'CUW', 'num_code' => '531', 'phone_code' => '599'],
            ['name' => 'Guernsey', 'code' => 'GGY', 'num_code' => '831', 'phone_code' => '44'],
            ['name' => 'Isle of Man', 'code' => 'IMN', 'num_code' => '833', 'phone_code' => '44'],
            ['name' => 'Jersey', 'code' => 'JEY', 'num_code' => '832', 'phone_code' => '44'],
            ['name' => 'Kosovo', 'code' => '---', 'num_code' => '0', 'phone_code' => '381'],
            ['name' => 'Saint Barthelemy', 'code' => 'BLM', 'num_code' => '652', 'phone_code' => '590'],
            ['name' => 'Saint Martin', 'code' => 'MAF', 'num_code' => '663', 'phone_code' => '590'],
            ['name' => 'Sint Maarten', 'code' => 'SXM', 'num_code' => '534', 'phone_code' => '1'],
            ['name' => 'South Sudan', 'code' => 'SSD', 'num_code' => '728', 'phone_code' => '211']
        ];

        foreach ($countries as $key => $value) {
            Country::create($value);
        }
    }
}